import { Category } from '../types';

export const CATEGORIES: Category[] = [
  {
    id: 'home',
    nameHe: 'בית',
    color: '#B088D0',
    subcategories: [
      { id: 'home-rent', nameHe: 'שכירות' },
      { id: 'home-mortgage', nameHe: 'משכנתא' },
      { id: 'home-arnona', nameHe: 'ארנונה' },
      { id: 'home-vaad', nameHe: 'ועד בית' },
      { id: 'home-electricity', nameHe: 'חשמל' },
      { id: 'home-water', nameHe: 'מים' },
      { id: 'home-gas', nameHe: 'גז' },
      { id: 'home-internet', nameHe: 'אינטרנט' },
      { id: 'home-cellular', nameHe: 'טלפון סלולרי' },
      { id: 'home-tv', nameHe: 'טלוויזיה / סטרימינג' },
      { id: 'home-maintenance', nameHe: 'תחזוקת הבית' },
      { id: 'home-repairs', nameHe: 'תיקונים' },
      { id: 'home-cleaning', nameHe: 'ניקיון / עוזרת בית' },
      { id: 'home-furniture', nameHe: 'רהיטים וציוד לבית' },
      { id: 'home-gardening', nameHe: 'גינה' },
    ],
  },
  {
    id: 'food',
    nameHe: 'אוכל וסופר',
    color: '#6AAF58',
    subcategories: [
      { id: 'food-grocery', nameHe: 'סופר' },
      { id: 'food-vegetables', nameHe: 'ירקות ופירות' },
      { id: 'food-bakery', nameHe: 'מאפייה' },
      { id: 'food-butcher', nameHe: 'קצביה' },
      { id: 'food-restaurants', nameHe: 'מסעדות' },
      { id: 'food-cafes', nameHe: 'בתי קפה' },
      { id: 'food-work', nameHe: 'אוכל בעבודה' },
      { id: 'food-kids-school', nameHe: 'אוכל לילדים לבית ספר' },
      { id: 'food-delivery', nameHe: 'משלוחים (וולט / טנא)' },
    ],
  },
  {
    id: 'transport',
    nameHe: 'רכב ותחבורה',
    color: '#7B6DC8',
    subcategories: [
      { id: 'transport-fuel', nameHe: 'דלק' },
      { id: 'transport-insurance', nameHe: 'ביטוח רכב' },
      { id: 'transport-license', nameHe: 'רישוי רכב' },
      { id: 'transport-service', nameHe: 'טיפולים לרכב' },
      { id: 'transport-test', nameHe: 'טסט לרכב' },
      { id: 'transport-parking', nameHe: 'חניה' },
      { id: 'transport-fines', nameHe: 'קנסות' },
      { id: 'transport-public', nameHe: 'תחבורה ציבורית' },
      { id: 'transport-taxi', nameHe: 'מונית / גט / אינדרייב' },
      { id: 'transport-lease', nameHe: 'ליסינג / החזר הלוואת רכב' },
    ],
  },
  {
    id: 'children',
    nameHe: 'ילדים',
    color: '#E8A850',
    subcategories: [
      { id: 'children-daycare', nameHe: 'מעון / פעוטון' },
      { id: 'children-kindergarten', nameHe: 'גן ילדים' },
      { id: 'children-school', nameHe: 'בית ספר' },
      { id: 'children-afterschool', nameHe: 'צהרון' },
      { id: 'children-activities', nameHe: 'חוגים' },
      { id: 'children-tutor', nameHe: 'שיעורים פרטיים' },
      { id: 'children-supplies', nameHe: 'ספרים וציוד לבית ספר' },
      { id: 'children-clothes', nameHe: 'בגדים לילדים' },
      { id: 'children-toys', nameHe: 'צעצועים' },
      { id: 'children-babysitter', nameHe: 'בייביסיטר' },
      { id: 'children-diapers', nameHe: 'חיתולים / טיפוח תינוק' },
    ],
  },
  {
    id: 'health',
    nameHe: 'בריאות',
    color: '#5AADE0',
    subcategories: [
      { id: 'health-kupat', nameHe: 'קופת חולים' },
      { id: 'health-supplement', nameHe: 'ביטוח משלים' },
      { id: 'health-medicine', nameHe: 'תרופות ובית מרקחת' },
      { id: 'health-doctor', nameHe: 'ביקור רופא' },
      { id: 'health-private', nameHe: 'רופאים פרטיים' },
      { id: 'health-dental', nameHe: 'רופא שיניים' },
      { id: 'health-optometry', nameHe: 'אופטיקה / עיניים' },
      { id: 'health-tests', nameHe: 'בדיקות רפואיות' },
      { id: 'health-therapy', nameHe: 'טיפולים (פיזיו, ריפוי בעיסוק)' },
      { id: 'health-mental', nameHe: 'בריאות הנפש / פסיכולוג' },
    ],
  },
  {
    id: 'education',
    nameHe: 'השכלה',
    color: '#E8C840',
    subcategories: [
      { id: 'education-university', nameHe: 'אוניברסיטה / מכללה' },
      { id: 'education-courses', nameHe: 'קורסים והכשרות' },
      { id: 'education-books', nameHe: 'ספרים ומקצועי' },
      { id: 'education-subscriptions', nameHe: 'מנויים מקצועיים' },
    ],
  },
  {
    id: 'personal',
    nameHe: 'טיפוח ואישי',
    color: '#C87AAE',
    subcategories: [
      { id: 'personal-haircut', nameHe: 'תספורת / מספרה' },
      { id: 'personal-cosmetics', nameHe: 'קוסמטיקה ואיפור' },
      { id: 'personal-beauty', nameHe: 'טיפולי יופי / מניקור' },
      { id: 'personal-gym', nameHe: 'חדר כושר / ספורט' },
      { id: 'personal-clothes', nameHe: 'בגדים' },
      { id: 'personal-shoes', nameHe: 'נעליים' },
      { id: 'personal-accessories', nameHe: 'תכשיטים ואביזרים' },
    ],
  },
  {
    id: 'entertainment',
    nameHe: 'בילויים ופנאי',
    color: '#E8B040',
    subcategories: [
      { id: 'entertainment-movies', nameHe: 'קולנוע / תיאטרון' },
      { id: 'entertainment-trips', nameHe: 'טיולים בארץ' },
      { id: 'entertainment-vacations', nameHe: 'חופשות בחו"ל' },
      { id: 'entertainment-culture', nameHe: 'אטרקציות ותרבות' },
      { id: 'entertainment-sports', nameHe: 'ספורט / כרטיסים' },
      { id: 'entertainment-hobbies', nameHe: 'תחביבים' },
    ],
  },
  {
    id: 'subscriptions',
    nameHe: 'מנויים ואפליקציות',
    color: '#68B898',
    subcategories: [
      { id: 'sub-netflix', nameHe: 'נטפליקס / Disney+' },
      { id: 'sub-spotify', nameHe: 'ספוטיפיי / מוזיקה' },
      { id: 'sub-news', nameHe: 'עיתונות דיגיטלית' },
      { id: 'sub-cloud', nameHe: 'אחסון ענן (iCloud, Google)' },
      { id: 'sub-software', nameHe: 'תוכנות ואפליקציות' },
      { id: 'sub-games', nameHe: 'משחקים' },
    ],
  },
  {
    id: 'shopping',
    nameHe: 'קניות כלליות',
    color: '#D07090',
    subcategories: [
      { id: 'shopping-pharmacy', nameHe: 'פארם / דראגסטור' },
      { id: 'shopping-gifts', nameHe: 'מתנות' },
      { id: 'shopping-online', nameHe: 'קניות אונליין (אמזון, אליאקספרס)' },
      { id: 'shopping-electronics', nameHe: 'אלקטרוניקה' },
      { id: 'shopping-home-goods', nameHe: 'מוצרי בית (איקאה, כלבו)' },
      { id: 'shopping-books', nameHe: 'ספרים' },
    ],
  },
  {
    id: 'pets',
    nameHe: 'חיות מחמד',
    color: '#D4A050',
    subcategories: [
      { id: 'pets-food', nameHe: 'מזון לחיות' },
      { id: 'pets-vet', nameHe: 'וטרינר' },
      { id: 'pets-grooming', nameHe: 'טיפוח' },
      { id: 'pets-accessories', nameHe: 'ציוד ואביזרים' },
    ],
  },
  {
    id: 'financial',
    nameHe: 'ביטוחים והלוואות',
    color: '#50A878',
    subcategories: [
      { id: 'financial-loans', nameHe: 'החזר הלוואה' },
      { id: 'financial-credit', nameHe: 'תשלומי אשראי' },
      { id: 'financial-life-insurance', nameHe: 'ביטוח חיים' },
      { id: 'financial-apartment-insurance', nameHe: 'ביטוח דירה' },
      { id: 'financial-nursing-insurance', nameHe: 'ביטוח סיעודי' },
      { id: 'financial-bank-fees', nameHe: 'עמלות בנק' },
    ],
  },
  {
    id: 'savings',
    nameHe: 'חיסכון',
    color: '#4A98D0',
    subcategories: [
      { id: 'savings-monthly', nameHe: 'חיסכון חודשי' },
      { id: 'savings-pension', nameHe: 'פנסיה / קרן פנסיה' },
      { id: 'savings-managers', nameHe: 'ביטוח מנהלים' },
      { id: 'savings-provident', nameHe: 'קופת גמל' },
      { id: 'savings-education', nameHe: 'קרן השתלמות' },
      { id: 'savings-emergency', nameHe: 'קרן חירום' },
      { id: 'savings-vacation', nameHe: 'חיסכון לחופשה' },
      { id: 'savings-car', nameHe: 'חיסכון לרכב' },
    ],
  },
  {
    id: 'investments',
    nameHe: 'השקעות',
    color: '#58A850',
    subcategories: [
      { id: 'invest-stocks', nameHe: 'מניות / תעודות סל' },
      { id: 'invest-real-estate', nameHe: 'נדל"ן' },
      { id: 'invest-crypto', nameHe: 'קריפטו' },
      { id: 'invest-bonds', nameHe: 'אגרות חוב' },
      { id: 'invest-mutual', nameHe: 'קרן נאמנות' },
      { id: 'invest-other', nameHe: 'השקעה אחרת' },
    ],
  },
  {
    id: 'holidays',
    nameHe: 'חגים ואירועים',
    color: '#C870D8',
    subcategories: [
      { id: 'holidays-rosh-hashana', nameHe: 'ראש השנה / יום כיפור' },
      { id: 'holidays-sukkot', nameHe: 'סוכות / שמחת תורה' },
      { id: 'holidays-hanuka', nameHe: 'חנוכה' },
      { id: 'holidays-purim', nameHe: 'פורים' },
      { id: 'holidays-pesach', nameHe: 'פסח' },
      { id: 'holidays-events', nameHe: 'אירועים משפחתיים (ברית, בר מצווה)' },
      { id: 'holidays-charity', nameHe: 'צדקה ותרומות' },
    ],
  },
  {
    id: 'other',
    nameHe: 'אחר',
    color: '#A0A0B0',
    subcategories: [
      { id: 'other-general', nameHe: 'כללי' },
    ],
  },
];

export const PAYMENT_METHODS = [
  { id: 'credit', nameHe: 'אשראי' },
  { id: 'cash', nameHe: 'מזומן' },
  { id: 'transfer', nameHe: 'העברה בנקאית' },
  { id: 'check', nameHe: "צ'ק" },
  { id: 'direct_debit', nameHe: 'הוראת קבע' },
] as const;
